// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"time"
)

type Donation struct {
	ID        int64
	Gateway   string
	Currency  string
	Role      string
	Donor     sql.NullInt64
	Amount    int64
	CreatedAt time.Time
}

type Poem struct {
	ID            int64
	Poet          sql.NullString
	Poetry        string
	ContextBefore string
	ContextAfter  string
	Verse         string
	Surah         string
	Tafsir        string
	VerseKey      string
}

type Report struct {
	ID        int64
	PoemID    int64
	Edit      string
	Checked   bool
	EditByID  sql.NullInt64
	CreatedAt time.Time
}

type User struct {
	ID        int64
	Username  string
	Password  string
	Role      string
	CreatedAt time.Time
}
