// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"time"
)

type Donation struct {
	ID        int64          `json:"id"`
	Gateway   string         `json:"gateway"`
	Currency  string         `json:"currency"`
	Role      string         `json:"role"`
	Donor     sql.NullInt64  `json:"donor"`
	Amount    int64          `json:"amount"`
	CreatedAt time.Time      `json:"created_at"`
}

type Poem struct {
	ID            int64          `json:"id"`
	Poet          sql.NullString `json:"poet"`
	Poetry        string         `json:"poetry"`
	ContextBefore string         `json:"context_before"`
	ContextAfter  string         `json:"context_after"`
	Verse         string         `json:"verse"`
	Surah         string         `json:"surah"`
	Tafsir        string         `json:"tafsir"`
	VerseKey      string         `json:"verse_key"`
}

type Quote struct {
	ID        int64          `json:"id"`
	Text      string         `json:"text"`
	Author    string         `json:"author"`
	Source    sql.NullString `json:"source"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

type Report struct {
	ID        int64          `json:"id"`
	PoemID    int64          `json:"poem_id"`
	Edit      string         `json:"edit"`
	Checked   bool           `json:"checked"`
	EditByID  sql.NullInt64  `json:"edit_by_id"`
	CreatedAt time.Time      `json:"created_at"`
}

type User struct {
	ID        int64     `json:"id"`
	Username  string    `json:"username"`
	Password  string    `json:"password"`
	Role      string    `json:"role"`
	CreatedAt time.Time `json:"created_at"`
}
